<?php
namespace app\admin\controller;

use think\Controller;

class Common extends Controller{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(!session('username')){
            $this->error('你没有权限，请登录！','admin/login/login');
        }
    }
}